services:
  frontend:
    build: frontend
    ports:
      - 3001:5173
    volumes:
      - ./frontend:/project
      - /project/node_modules
  backend:
    build: backend
    ports:
      - 3000:8000
    volumes:
      - ./backend:/project